### ISSUE TITLE
Not an issue: how to get passthrough video?

### ISSUE THREAD

**Issue by Ceebox** [catid/XRmonitors#3]
I want to get passthrough video from my WMR headset and display it on my monitor (I know it slightly overlaps).

Any help would be nice, and I see they have done it here, yet I cannot seem to find the code or figure it out myself.

**Comment by catid** [comment]
You can find the related code with this search:

https://github.com/catid/XRmonitors/search?q=implant&unscoped_q=implant

**Comment by Ceebox** [comment]
Thanks!
